### ISSUE TITLE
No such module 'TMXProfiling'

### ISSUE THREAD

**Issue by alexstich** [yoomoney/yandex-checkout-payments-swift#73]
При сборке проекта выскакивает ошибка

/Users/alex/project/Pods/YandexCheckoutPayments/YandexCheckoutPayments/Private/Services/ThreatMetrix/ThreatMetrixService.swift:25:8: No such module 'TMXProfiling'

Менедежер яндекса скинул нам только TrustDefender,  мы его установили.
версия yandex-checkout-payments-swift 3.7.1

TMXProfiling надо устанавливать помимо TrustDefender? И где его брать?

**Comment by oltv00** [comment]
@alexstich 
Необходимо запросить у менеджера фреймворки TMXProfiling и TMXProfilingConnections
TrustDefender уже не нужен, его можно удалить.

**Comment by kcrebound** [comment]
вот это можно закрыть, думаю

**Comment by alexstich** [comment]
Да.
