### ISSUE TITLE
Интеграция в Objective C проект

### ISSUE THREAD

**Issue by PackagedCat** [yoomoney/yandex-checkout-payments-swift#79]
Возможно ли интеграция данной библиотеки в проект Objective C? В заголовочном файле YandexCheckoutPayments.h описаны только поля версии библиотеки, может есть файл с полным описанием классов?

**Comment by oltv00** [comment]
>Возможно ли интеграция данной библиотеки в проект Objective C?

https://github.com/oltv00/msdk-objc
В objective-c можно попробовать интегрировать вот так.

>может есть файл с полным описанием классов?

не очень понимаю о каком описании речь, можно подробнее?

**Comment by PackagedCat** [comment]
> не очень понимаю о каком описании речь, можно подробнее?
Имел ввиду заголовочные файлы .h, в котором были бы экспортированы классы из Swift
> https://github.com/oltv00/msdk-objc
Насколько я понял, нужно писать прослойку между Swift и Objective C?

**Comment by oltv00** [comment]
>Имел ввиду заголовочные файлы .h, в котором были бы экспортированы классы из Swift

нет, такого нет

>Насколько я понял, нужно писать прослойку между Swift и Objective C?

да, все верно

**Comment by PackagedCat** [comment]
Спасибо, получилось! Наконец дело сдвинулось с мертвой точки :)
